package com.composetest.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8B5000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFA643)
val onPrimaryContainerLight = Color(0xFF452500)
val secondaryLight = Color(0xFF815524)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFCB9A)
val onSecondaryContainerLight = Color(0xFF5D3707)
val tertiaryLight = Color(0xFF436087)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF829FC9)
val onTertiaryContainerLight = Color(0xFF001024)
val errorLight = Color(0xFF9C000B)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFE10016)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF231A11)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF231A11)
val surfaceVariantLight = Color(0xFFF8DEC8)
val onSurfaceVariantLight = Color(0xFF554434)
val outlineLight = Color(0xFF887361)
val outlineVariantLight = Color(0xFFDBC2AD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E25)
val inverseOnSurfaceLight = Color(0xFFFFEEE1)
val inversePrimaryLight = Color(0xFFFFB870)
val surfaceDimLight = Color(0xFFE9D7C9)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E7)
val surfaceContainerLight = Color(0xFFFDEBDC)
val surfaceContainerHighLight = Color(0xFFF7E5D7)
val surfaceContainerHighestLight = Color(0xFFF1DFD1)

val primaryDark = Color(0xFFFFCA97)
val onPrimaryDark = Color(0xFF4A2800)
val primaryContainerDark = Color(0xFFF69300)
val onPrimaryContainerDark = Color(0xFF331A00)
val secondaryDark = Color(0xFFF6BB81)
val onSecondaryDark = Color(0xFF4A2800)
val secondaryContainerDark = Color(0xFF5A3404)
val onSecondaryContainerDark = Color(0xFFFFC58E)
val tertiaryDark = Color(0xFFABC8F5)
val onTertiaryDark = Color(0xFF0F3156)
val tertiaryContainerDark = Color(0xFF59769F)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFFD10013)
val onErrorContainerDark = Color(0xFFFFFFFF)
val backgroundDark = Color(0xFF1A120A)
val onBackgroundDark = Color(0xFFF1DFD1)
val surfaceDark = Color(0xFF1A120A)
val onSurfaceDark = Color(0xFFF1DFD1)
val surfaceVariantDark = Color(0xFF554434)
val onSurfaceVariantDark = Color(0xFFDBC2AD)
val outlineDark = Color(0xFFA38D7A)
val outlineVariantDark = Color(0xFF554434)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DFD1)
val inverseOnSurfaceDark = Color(0xFF392E25)
val inversePrimaryDark = Color(0xFF8B5000)
val surfaceDimDark = Color(0xFF1A120A)
val surfaceBrightDark = Color(0xFF42372D)
val surfaceContainerLowestDark = Color(0xFF150D06)
val surfaceContainerLowDark = Color(0xFF231A11)
val surfaceContainerDark = Color(0xFF271E15)
val surfaceContainerHighDark = Color(0xFF32281F)
val surfaceContainerHighestDark = Color(0xFF3E3329)

internal val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
